In [12]:
# Shuffle

import numpy as np

var1 = np.array([1,2,3,4,5])
np.random.shuffle(var1)

print(var1)

[2 5 1 4 3]


In [17]:
# Unique

var2 = np.array([1,2,4,4,2,3,3,4,6,0,1])
print(np.unique(var2,return_index=True,return_counts=True))  #Returns an array of unique values in

(array([0, 1, 2, 3, 4, 6]), array([9, 0, 1, 5, 2, 8]), array([1, 2, 2, 2, 3, 1]))


In [21]:
# Resize

var3 = np.array([1,2,3,4,5,6])

print(np.resize(var3,(2,3)))

[[1 2 3]
 [4 5 6]]


In [24]:
# Flatten Ravel 

var4 = np.array([1,2,3,4,5,6])
y=np.resize(var4,(2,3))
print(var4)
print("Flatten : ",y.flatten(order='F'))
print("Ravel : ",np.ravel(y))

[1 2 3 4 5 6]
Flatten :  [1 4 2 5 3 6]
Ravel :  [1 2 3 4 5 6]
Flatten :  [1 4 2 5 3 6]
