# Arithmetic Operations

# oneDimensional Array

In [6]:
import numpy as np

#addition
# for different arithmetic operations just replace + -> - * / ^ or ** in the line 10 and 15.
# reciprocal 1/num=ans
var1=np.array([1,2,3,4])
var1add = var1+3
var1add

var2 = np.array([1,2,3,4])
var3 = np.array([1,2,3,4])
var23add = var2+var3
var23addF = np.add(var2,var3) #using function
print(var23add) 
print(var23add)

[2 4 6 8]
[2 4 6 8]


# twoDimensional Array

In [7]:
var2d1 = np.array([1,2,3])
var2d2 = np.array([1,2,3])

var2dAdd = np.add(var2d1,var2d2)

print(var2dAdd)

[2 4 6]


# Arithmetic Functions

types of arithmetis functions : 
np.min()
np.max()
np.argmin()
np.sqrt()
np.sin()
np.cos()
np.cumsum()

In [11]:
num = np.array([1,2,3,4])

print("min: ",np.min(num),np.argmin(num)) # position of the  minimum value in array  
print("max: ",np.max(num),np.argmax(num)) # position of the  maximum value in array

min:  1 1
max:  4 4


In [16]:
# axis 0= column , 1 = row
num2 = np.array([[1,2,3],[7,1,4]])
print("min: ",np.min(num2,axis=0))
print("min: ",np.min(num2,axis=1))
print("\n")
print("max: ",np.max(num2,axis=0))
print("max: ",np.max(num2,axis=1))

min:  [1 1 3]
min:  [1 1]


max:  [7 2 4]
max:  [3 7]


In [23]:
print("sqrt of 1d: ",np.sqrt(num))
print("sqrt of 2d: ",np.sqrt(num2))

sqrt of 1d:  [1.         1.41421356 1.73205081 2.        ]
sqrt of 2d:  [[1.         1.41421356 1.73205081]
 [2.64575131 1.         2.        ]]


In [26]:
#sin and cos

sin1 = np.array([1,2,3])
print("sin: ",np.sin(sin1))
print("cos: ",np.cos(sin1))

sin:  [0.84147098 0.90929743 0.14112001]
cos:  [ 0.54030231 -0.41614684 -0.9899925 ]


In [27]:
#cumsum / smmation

cumsum1 = np.array([1,2,3,4,5])
print(f"Input array: {np.cumsum(cumsum1)}")

Input array: [ 1  3  6 10 15]
