In [1]:
import numpy as np
x=np.array([1,2,3])
y=np.array([4,5,6])

In [2]:
print(x+y) 

[5 7 9]


In [3]:
x=np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
x.ndim #output how many dimension  the array has
x.dtype #output what data type is used to store the elements of this array  

dtype('int64')

In [5]:
np.array([[1,2,3],[4,5,6]],float).dtype # can create floating type by passing  dtype=float
# output: float64

dtype('float64')

In [6]:
x.shape # number of rows and columns 

(2, 3)

In [7]:
x=np.array([5,5,5])
x.sum()

15

In [8]:
x=np.array([1,2,3,4,5,6])
x_reshaped = x.reshape((2,3)) # rows and columns  of the reshaped array are 3 and 2 respectively
x_reshaped



array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
x_reshaped[1,2] # return value of 2 row and 3 column which is 6

6

In [10]:
# also can manupulate with reshape
x_reshaped[0,0]=2
x_reshaped

array([[2, 2, 3],
       [4, 5, 6]])

In [5]:
# get array from user and print 
import numpy as np
ls=[]
for i in range(1,5):
    lsInput=int(input("Enter data: "))
    ls.append(lsInput)
print(np.array(ls))

[10 20 30 40]
