# Broadcasting

broadcasting is a mechanism that allows arrays of different shapes to be combined together in element-wise operations. However, sometimes you might encounter broadcasting errors when trying to perform operations on arrays with incompatible shapes.

In [4]:
import numpy as np

var1 = np.array([1,2,3])
var2 = np.array([1,2])
# print(var1+var2)  # This will give an error because arrays are not added element-wise by default in NumPy
var2 = np.array([[1],[2],[3]]) 
print(var1+var2) # both array should have atleast one to them then it can perfoem arithmetic operation with each other



[[2 3 4]
 [3 4 5]
 [4 5 6]]
