In [4]:
import numpy as np
var = np.array([6,7,8,9])
              # 0,1,2,3
              # -4,-3,-2,-1
                
print(var[-1])
print(var[3])

9
9


# 2D array

In [8]:
var2 = np.array([[1,2,3],[4,5,6]])
print(var2[0,0])
print(var2[0,1])
print(var2[0,2])
print(var2[1,0])
print(var2[1,1])
print(var2[1,2])

1
2
3
4
5
6


# 3D array

In [12]:
var3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(var3[0][:,0]) 
print(var3[0][:,1]) 
print(var3[0][:,2]) 

print(var3[0,1,1])

[1 4 7]
[2 5 8]
[3 6 9]
5
