# Insert

In [20]:
import numpy as np

var1 = np.array([1,2,3,4,5])

print(var1)
np.insert(var1,(0,4),6)

np.append(var1,6.5) # can insert float value unlike  insert method


[1 2 3 4 5]


array([1. , 2. , 3. , 4. , 5. , 6.5])

In [25]:
# 2D array
var2 = np.array([[1,2,6],[3,4,5]])

print(var2)
np.insert(var2,2,6,axis=0)
np.insert(var2,2,6,axis=1)

np.insert(var2,0,[0,0,0],axis=0)

np.delete(var2,[0,1],axis=1)


[[1 2 6]
 [3 4 5]]


array([], shape=(0, 3), dtype=int64)