# JOIN & SPLIT

join : combinig two or more array into single array

In [14]:
import numpy as np

var1 = np.array([1,2,3,4])
var2 = np.array([5,6,7,8])

var3 = np.array([[1,2],[3,4]])
var4 = np.array([[5,6],[7,8]])

ar1 = np.concatenate((var1,var2))

#1D
arAxis0 = np.concatenate((var1,var2),axis=0)

#2D
arAxis1 = np.concatenate((var3,var4),axis=0)
arAxis2 = np.concatenate((var3,var4),axis=1)

print(ar1,"\n")
print(arAxis0,"\n")
print(arAxis1,"\n")
print(arAxis2,"\n")

[1 2 3 4 5 6 7 8] 

[1 2 3 4 5 6 7 8] 

[[1 2]
 [3 4]
 [5 6]
 [7 8]] 

[[1 2 5 6]
 [3 4 7 8]] 



In [18]:
#stack function

var6 = np.array([1,2,3,4,5])
var7 = np.array([1,2,3,4,5])

arnew = np.stack((var6,var7))
arnewH = np.hstack((var6,var7))
arnewV = np.vstack((var6,var7))
arnewD = np.dstack((var6,var7))

print(arnew,"\n")
print(arnewH,"\n") # row
print(arnewV,"\n") # column
print(arnewD,"\n") # height

[[1 2 3 4 5]
 [1 2 3 4 5]] 

[1 2 3 4 5 1 2 3 4 5] 

[[1 2 3 4 5]
 [1 2 3 4 5]] 

[[[1 1]
  [2 2]
  [3 3]
  [4 4]
  [5 5]]] 



splitting : divide array into multiple smaller array.

In [22]:
#1D Array

var8 = np.array([1,2,3,4,5,6,7,8,9])

split1D= np.array_split(var8,3)
print(split1D)

for i in split1D:
    print(i)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
[1 2 3]
[4 5 6]
[7 8 9]


In [30]:
#2D array

var9 = np.array([[1,2,5],[3,4,6]])

split2D = np.array_split(var9, 2)
print(split2D)

for i in split2D:
    print(i)

[array([[1, 2, 5]]), array([[3, 4, 6]])]
[[1 2 5]]
[[3 4 6]]
