# MATRIX IN NUMPY ARRAY

In [8]:
import numpy as np

matrix1 = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
matrix2 = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(matrix1)
print(matrix1*matrix2)
print(matrix1.dot(matrix2))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
