# Matrix Functions
- transpose
- swapaxes
- inverse
- power
- determinate

In [16]:
import numpy as np

var1 = np.matrix([[1,2,3],[4,5,6],[7,8,9]])

print(np.transpose(var1),"\n")

print(np.swapaxes(var1,1,1), "\n")
print(np.linalg.inv(var1))
print(np.linalg.matrix_power(var1,0)) # identity matrix

print(np.linalg.det(var1))

[[1 4 7]
 [2 5 8]
 [3 6 9]] 

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
-9.51619735392994e-16
