# rand() function

In [7]:
import numpy as np
# print within 0 and 1 only
var = np.random.rand(4)
var

array([0.91721354, 0.66190245, 0.76148209, 0.83405766])

In [9]:
var1=np.random.rand(2,4)
var1

array([[0.22337447, 0.54474796, 0.54464696, 0.31388411],
       [0.20073312, 0.64724374, 0.87248969, 0.47115874]])

# randn()

In [12]:
# returns number near to zero. can be positive and negitive
var2 = np.random.randn(5)
var2

array([ 2.15896381, -0.65065102, -0.39074778, -0.829148  , -0.63203914])

# ranf()

In [19]:
# random sampling in numpy

var3=np.random.ranf(4)
var3

array([0.8579064 , 0.30435793, 0.99687631, 0.13905571])

# randint()

In [37]:
# returns random number between specific range
var4 = np.random.randint(1,10,5)
var4

array([8, 3, 8, 3, 1])