In [3]:
import numpy as np

# creating array that contains only zeros

zeros = np.zeros(5)
zeros2 = np.zeros((2,2))
zeros2

array([[0., 0.],
       [0., 0.]])

# array that contains only 1s

In [6]:
# creating array that contains only ones

ar_one = np.ones(4)
ar_one2 = np.ones((2,5))
ar_one2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# empty array

In [7]:
ar_empty = np.empty(5)
ar_empty

array([0., 0., 0., 0., 0.])

# Range

In [8]:
ar_rn = np.arange(4)
ar_rn

array([0, 1, 2, 3])

# array that contains 1s diagonally

In [15]:
ar_di = np.eye(3,3)
ar_di

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# linspace

In [23]:
ar_lin = np.linspace(0,10,num=5)
ar_lin

array([ 0. ,  2.5,  5. ,  7.5, 10. ])