# Shape

In [8]:
import numpy as  np
var = np.array([[1,2,3,4],[1,2,3,4]])
print(var.shape) #(rows,columns)

(2, 4)


# Reshape

In [19]:
var2 = np.array([1,2,3,4,5,6,7,8])
print(var2.reshape(4,2))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [28]:
#convert into 3d array

var3 = np.array([1,2,3,4,5,6,7,8])
print(var3.reshape(2,2,2)) # (rows,rows inside  brackets,colums inside rows)

one = var3.reshape(-1)
print("\n",one)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

 [1 2 3 4 5 6 7 8]
