In [3]:
# 2D array
import numpy as np
ar2 = np.array([[1,2,3,4],[1,2,3,4]]) # have to insert same number of data in both bracates
ar2

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [5]:
ar3=np.array([[[1,2,3],[1,2,3],[1,2,3]]])
ar3

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

In [6]:
# to create n dimensional array

arN = np.array([1,2,3],ndmin=10)
arN

array([[[[[[[[[[1, 2, 3]]]]]]]]]])